### ISSUE TITLE
Where are the sources?

### ISSUE THREAD

**Issue by gbtami** [lukasmonk/lucaschessR#1]
Great news! I like to test it on Ubuntu 18.04 but without source files it is not possible :)

**Comment by lukasmonk** [comment]
To test in Ubuntu it is needed to add some code and some engines.
Folder bin/OS to create a folder to support Ubuntu.
My idea was to get stability in win32 then work in the support of Linux.

Source ?  https://github.com/lukasmonk/lucaschessR and clone, folder bin/

**Comment by gbtami** [comment]
Ahh, I'm blind. Sry for the noise!
