### ISSUE TITLE
Runtime error under Wine/Linux

### ISSUE THREAD

**Issue by akoun** [lukasmonk/lucaschessR#11]
Hello,

I've just installe the wonderful LucasChess R1.00 under Linux/Wine.
Everything runs perfectly except for one thing
Under the Options-Configuration when I click the 'Accept' button the program bombs with a runttime error. Interestingly if I do some modification (e.g. Player's nale or other) the modification is saved before the runtime error.

My config: Debian 10, Wine 5.0 (I tested both under 32b or 64b wineprefix with the same result.)
I include the windows debugger output in case it says something meaningful to someone...

best regards,
akoun

-----------
0x7bcb3e84: int	$3
Modules:
Module	Address			Debug info	Name (37 modules)
PE	  400000-  421000	Export          lucasr
PE	10000000-10365000	Export          python37
PE	7b020000-7b023000	Deferred        kernelbase
PE	7b420000-7b5db000	Export          kernel32
PE	7bc30000-7bc34000	Deferred        ntdll
PE	7dbe0000-7dbe4000	Deferred        uxtheme
PE	7dc20000-7dc23000	Deferred        usp10
PE	7dc90000-7dd0e000	Deferred        comctl32
PE	7de90000-7de94000	Deferred        rpcrt4
PE	7df20000-7df2f000	Deferred        setupapi
PE	7e180000-7e184000	Deferred        winex11
PE	7e8c0000-7e904000	Deferred        crypt32
PE	7e9b0000-7e9b4000	Deferred        bcrypt
PE	7e9d0000-7e9d4000	Deferred        rsaenh
PE	7ea10000-7ea13000	Deferred        api-ms-win-core-path-l1-1-0
PE	7ea30000-7ea34000	Deferred        imm32
PE	7f070000-7f073000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	7f080000-7f083000	Deferred        api-ms-win-crt-conio-l1-1-0
PE	7f090000-7f093000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	7f0b0000-7f0b3000	Deferred        api-ms-win-crt-process-l1-1-0
PE	7f0c0000-7f0c3000	Deferred        api-ms-win-crt-environment-l1-1-0
PE	7f0d0000-7f0d3000	Deferred        api-ms-win-crt-time-l1-1-0
PE	7f0f0000-7f0f4000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	7f100000-7f104000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	7f120000-7f124000	Deferred        api-ms-win-crt-string-l1-1-0
PE	7f130000-7f133000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	7f150000-7f155000	Deferred        api-ms-win-crt-math-l1-1-0
PE	7f160000-7f164000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	7f1a0000-7f2be000	Export          ucrtbase
PE	7f1a0000-7f2be000	Export          ws2_32
PE	7f2e0000-7f2e4000	Deferred        advapi32
PE	7f370000-7f377000	Deferred        gdi32
PE	7f4e0000-7f5c8000	Deferred        user32
PE	7f700000-7f708000	Deferred        shlwapi
PE	7f780000-7f784000	Deferred        msvcrt
PE	7ffc0000-7ffd3000	Deferred        vcruntime140
PE	7ffc0000-7ffd3000	Deferred        version
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000028    0
	0000001a    0
	00000013    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	00000017    0
	00000016    0
	00000012    0
00000018 winedevice.exe
	00000020    0
	0000001d    0
	0000001c    0
	0000001b    0
	00000019    0
00000026 winedevice.exe
	0000002b    0
	0000002a    0
	00000029    0
	00000027    0
00000030 explorer.exe
	00000036    0
	00000035    0
	00000034    0
	00000031    0
0000005b (D) C:\Program Files\LucasChessR\bin\LucasR.exe
	0000005f    0
	0000005c    0 <==
System information:
    Wine build: wine-5.0 (Debian 5.0-4)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 5.9.0-1-amd64

**Comment by lukasmonk** [comment]
Thanks, I have no idea what it means.
When accepted after setup, the program is restarted, that's where the problem occurs.
It is not a problem that affects the use of the program, except that when kibitzers are launched, for example, which launch another session of the program, they give the same error.

**Comment by rchastain** [comment]
@lukasmonk 
By the way, do you intend to make a Linux version?

**Comment by lukasmonk** [comment]
I have installed a Linux virtual machine with Linux Mint 64 cinnamon. It has Python 3.8 pre-installed, in the future version for windows I will try to make it 3.8 too.
Without much effort, I have managed to make it work, although it works poorly, because there is still work on the adaptation.
In my roadmap for version 2.0, there is the attempt to get a version that works correctly on Linux 64.

**Comment by rchastain** [comment]
> Without much effort, I have managed to make it work, although it works poorly, because there is still work on the adaptation.
> In my roadmap for version 2.0, there is the attempt to get a version that works correctly on Linux 64.

Great! If I can I would be glad to help.

**Comment by akoun** [comment]
This error also occurs when clicking Information/Check for updates to go from R1.00 to R1.01...
So every time the application is restarted after some UI action the error occurs.

**Comment by lukasmonk** [comment]
There is other thread with the same problem.
