### ISSUE TITLE
something small that needs fixing

### ISSUE THREAD

**Issue by Batu-64** [lukasmonk/lucaschessR#12]
After making a color change in the game, the user has to undo 1 move to continue the game.
I wish you success.

**Comment by lukasmonk** [comment]
Sorry, I don't know how to replicate the problem. My test has been: Playing against any engine, after some moves, menu Config-Change opponent.

**Comment by lukasmonk** [comment]
Color is not side, now I understand

**Comment by lukasmonk** [comment]
Fixed, thank you very much.

**Comment by lukasmonk** [comment]
Fixed and published, thank you very much.

**Comment by Batu-64** [comment]
Version: R 1.07
After adjourn the game, I cannot continue the game by choosing to adjournments.

**Comment by Batu-64** [comment]
Version: R 1.07
After adjourn the game, I cannot continue the game by choosing to adjournments. It doesn't work the Cancel button on the same screen.

**Comment by lukasmonk** [comment]
Fixed in my code, I will published this week a new update.
Thank you very much for the feedback
