### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by rchastain** [lukasmonk/lucaschessR#13]
Hello!
Is the new version (1.04) ready for Linux? I had tried without success to compile the previous version. If you confirm that the new version can be compiled for Linux, I will make a new attempt.
Regards.
Roland

**Comment by lukasmonk** [comment]
My forecast is that in version 2.0 compatible code will be available and something tested.

**Comment by rchastain** [comment]
Thank you for your answer. I close the issue.
