### ISSUE TITLE
"Move selected by the player" is not working

### ISSUE THREAD

**Issue by cja000** [lukasmonk/lucaschessR#15]
Hi,

Thank you so much for this new R version of your wonderful program.

I'm trying to use the "Move selected by the player" option in "Play against an engine" but it is not working.
![image](https://user-images.githubusercontent.com/25002014/105640205-0c95d100-5e7d-11eb-9343-29aac4d1dafe.png)

I can change it in the configuration but in the game it is not working. I cannot choose the move.
I think that the same happens with the "Resign/draw by engine" option (this is more difficult to assure)

Is it working?

Thanks
C.

**Comment by lukasmonk** [comment]
Fixed both bugs, to the next update.
Thanks for the feedback.
