### ISSUE TITLE
lucas chess tutor/help to move/eval often stuck

### ISSUE THREAD

**Issue by fvannee** [lukasmonk/lucaschessR#16]
I'm using 1.05a on Windows, installer version from the website.

Unfortunately I don't have a 100% way of reproducing this, but it happens often enough for me. I'll try to describe as detailed as possible at least how I'm using it and hope that'll be helpful.

I'm playing custom games:

Play -> Play against an engine -> 
I tried with several StockFish engines, but for example "Select StockFish 12 64 bits (1650)"
Play

I have a Tutor enabled, set to StockFish 12 64 bits, 6 seconds limit, depth --.
During the game, every now and then I press "Help to Move", or "try again" when the tutor tells me I need to do something different.
Now, the problem that often happens is that after a while "Help to Move" will seemingly just be stuck. The small popup with "analyzing" appears (and goes away again), but there's no popup with the move that it suggests.
Also, when making a move, the eval in the table with moves that have been done already, is generally (+0.00) from there on.
I can press "Help to Move" after that as much as I like, but it will never display help from then on. I end up needing to do something like: save the game to a file, restart lucas chess, then load the game from the file. (Side note: there doesn't actually seem to be a very easy way to do this - when loading the .pbn file again, it brings you in some sort of analysis mode, rather than the actual "custom game" mode that I was in before)

Any idea what this could be?

**Comment by fvannee** [comment]
Probably unrelated, but sometimes the "tutor" also says my move is bad with eval +0.00, even though the move is definitely not exactly +0.00 (it happens quite often that it's exactly this +0.00 that it complains about). Probably the engine doesn't even fully compute that move or so, but knows that it's worse than the move that should be made.

![image](https://user-images.githubusercontent.com/1274053/105907068-d1360680-6024-11eb-8c0b-009491a1e77b.png)

**Comment by lukasmonk** [comment]
Thanks for the feedback.
I will study it, these week.

**Comment by lukasmonk** [comment]
I have published a new update.

On the other hand, in configuration:

![image](https://user-images.githubusercontent.com/6254278/106367973-b4604280-6346-11eb-9bed-8b4d13d3c198.png)
