### ISSUE TITLE
Export bin book fails with Polyglot book factory

### ISSUE THREAD

**Issue by Jonathan003** [lukasmonk/lucaschessR#20]
When I go to Polyglot book factory. And I create a new project, and import an existing bin book, noting happens.
I want to use this option to import a bin book, and export it to a new bin book with the option 'Uniform'.

I have made a video capture of it:

https://user-images.githubusercontent.com/40061628/106786684-1d013500-664f-11eb-91b1-3f62b7e551f0.mp4

**Comment by Jonathan003** [comment]
This problem is solved with version 1.09.
But there is still a problem to export the bin book.
The latest version where it works to export a bin book is LucasChessR 33d
But there is also some small issue with this version, that is that you first have to restart LucasChessR 33d, in order to be able to export the bin book.

**Comment by lukasmonk** [comment]
I´ll try to fix it in the next update.

**Comment by Jonathan003** [comment]
Thanks for the quick fix!
This works in version R1.10
