### ISSUE TITLE
LucasR.exe crashes when run via Wine

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschessR#24]
I installed LucasChessR (for which, thanks) on Linux Mint 20.1 x64. When I run the program - as against the installer - I see this:

![image](https://user-images.githubusercontent.com/47056543/108652764-d15ae200-74bc-11eb-99e5-222cefd56dfc.png)

The default for my version of Wine (5.0.1) is to emulate Windows 8.1. But telling it to emulate Windows 10 did not remove the error. And the program does not run. LucasChess - the non-'R' version - runs pretty much fine on my system.

The Wine debugger (offered in the window shown in the screenshot) produces the following.

```
0x7bcae6f0 DbgBreakPoint in ntdll: int	$3
Modules:
Module	Address			Debug info	Name (84 modules)
PE	  230000-  233000	Deferred        api-ms-win-crt-time-l1-1-0
PE	  240000-  243000	Deferred        api-ms-win-crt-process-l1-1-0
PE	  400000-  421000	Export          lucasr
PE	10000000-10365000	Export          python37
PE	61740000-61743000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	622c0000-622c3000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	62340000-623be000	Deferred        uxtheme
PE	62800000-628bc000	Deferred        usp10
PE	63340000-63344000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	63a00000-63a03000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	65980000-6599a000	Deferred        version
PE	66700000-66781000	Deferred        rsaenh
PE	68c40000-68d3d000	Deferred        shlwapi
PE	69580000-69584000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	69d80000-69d83000	Deferred        api-ms-win-crt-environment-l1-1-0
PE	6a900000-6aa75000	Deferred        setupapi
PE	6b680000-6b68c000	Deferred        api-ms-win-core-path-l1-1-0
PE	6c0c0000-6c0fb000	Deferred        imm32
PE	6d780000-6d784000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	6df80000-6df84000	Deferred        api-ms-win-crt-string-l1-1-0
PE	6e8c0000-6ec8c000	Deferred        comctl32
PE	6ecc0000-6ecd3000	Deferred        vcruntime140
PE	6ee80000-6ee83000	Deferred        api-ms-win-crt-conio-l1-1-0
PE	6fdc0000-6ff8e000	Deferred        rpcrt4
PE	70780000-70785000	Deferred        api-ms-win-crt-math-l1-1-0
PE	7b000000-7b274000	Deferred        kernelbase
ELF	7b400000-7b671000	Dwarf           kernel32<elf>
  \-PE	7b420000-7b671000	\               kernel32
ELF	7bc00000-7beae000	Dwarf           ntdll<elf>
  \-PE	7bc30000-7beae000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d5ff000-7d607000	Deferred        libxfixes.so.3
ELF	7d607000-7d614000	Deferred        libxcursor.so.1
ELF	7d614000-7d629000	Deferred        libxi.so.6
ELF	7d629000-7d62e000	Deferred        libxcomposite.so.1
ELF	7d62e000-7d63d000	Deferred        libxrandr.so.2
ELF	7d63d000-7d649000	Deferred        libxrender.so.1
ELF	7d749000-7d768000	Deferred        libbsd.so.0
ELF	7d768000-7d797000	Deferred        libxcb.so.1
ELF	7d797000-7d8e6000	Deferred        libx11.so.6
ELF	7d943000-7d94b000	Deferred        libxxf86vm.so.1
ELF	7d94b000-7d950000	Deferred        libxinerama.so.1
ELF	7d950000-7d958000	Deferred        libxdmcp.so.6
ELF	7d958000-7d95e000	Deferred        libxau.so.6
ELF	7d95e000-7d975000	Deferred        libxext.so.6
ELF	7d975000-7da2e000	Deferred        winex11<elf>
  \-PE	7d990000-7da2e000	\               winex11
ELF	7da2e000-7da38000	Deferred        libffi.so.7
ELF	7da38000-7dac8000	Deferred        libgmp.so.10
ELF	7dac8000-7db01000	Deferred        libhogweed.so.5
ELF	7db01000-7db41000	Deferred        libnettle.so.7
ELF	7db41000-7db58000	Deferred        libtasn1.so.6
ELF	7db58000-7dcda000	Deferred        libunistring.so.2
ELF	7dcda000-7dcfa000	Deferred        libidn2.so.0
ELF	7dcfa000-7de52000	Deferred        libp11-kit.so.0
ELF	7de52000-7e052000	Deferred        libgnutls.so.30
ELF	7e07c000-7e171000	Deferred        crypt32<elf>
  \-PE	7e0a0000-7e171000	\               crypt32
ELF	7e171000-7e195000	Deferred        bcrypt<elf>
  \-PE	7e180000-7e195000	\               bcrypt
ELF	7e213000-7e21d000	Deferred        libuuid.so.1
ELF	7e21d000-7e249000	Deferred        libexpat.so.1
ELF	7e249000-7e297000	Deferred        libfontconfig.so.1
ELF	7e297000-7e2b5000	Deferred        libz.so.1
ELF	7e2b5000-7e2f4000	Deferred        libpng16.so.16
ELF	7e2f4000-7e3ba000	Deferred        libfreetype.so.6
ELF	7e3ef000-7e508000	Dwarf           ucrtbase<elf>
  \-PE	7e420000-7e508000	\               ucrtbase
ELF	7e508000-7e543000	Deferred        ws2_32<elf>
  \-PE	7e510000-7e543000	\               ws2_32
ELF	7e543000-7e775000	Deferred        user32<elf>
  \-PE	7e570000-7e775000	\               user32
ELF	7e775000-7e8cc000	Deferred        gdi32<elf>
  \-PE	7e790000-7e8cc000	\               gdi32
ELF	7e8cc000-7e94f000	Deferred        advapi32<elf>
  \-PE	7e8e0000-7e94f000	\               advapi32
ELF	7e94f000-7ea23000	Deferred        msvcrt<elf>
  \-PE	7e970000-7ea23000	\               msvcrt
ELF	7eed1000-7efd6000	Deferred        libm.so.6
ELF	f7bc9000-f7bcf000	Deferred        libdl.so.2
ELF	f7bcf000-f7dbe000	Deferred        libc.so.6
ELF	f7dbe000-f7de1000	Deferred        libpthread.so.0
ELF	f7e0b000-f7fbe000	Dwarf           libwine.so.1
ELF	f7fc0000-f7fed000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000026    0
	0000001a    0
	00000013    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	00000017    0
	00000016    0
	00000012    0
00000018 winedevice.exe
	00000020    0
	0000001d    0
	0000001c    0
	0000001b    0
	00000019    0
0000001e explorer.exe
	00000023    0
	00000022    0
	00000021    0
	0000001f    0
00000024 winedevice.exe
	00000029    0
	00000028    0
	00000027    0
	00000025    0
0000002a (D) C:\users\[redactedUsername]\Local Settings\Application Data\Programs\LucasChessR\bin\LucasR.exe
	00000032    0
	0000002b    0 <==
0000002c winecfg.exe
	0000002d    0
0000002e winecfg.exe
	0000002f    0
System information:
    Wine build: wine-5.0.1
    Platform: i386 (WOW64)
    Version: Windows 8.1
    Host system: Linux
    Host version: 5.8.0-43-generic

```

**Comment by lukasmonk** [comment]
I have no idea what the reason may be, I have tried several versions and none have worked. I will continue testing, in parts, trying to find out what is bothering him.

**Comment by lukasmonk** [comment]
It works when started directly:
![image](https://user-images.githubusercontent.com/6254278/108757988-da929000-754a-11eb-9f44-315102fa0709.png)

**Comment by lukasmonk** [comment]
The link created by wine does not work, it needs some change, such as starting the program from the folder where it is installed.

**Comment by LinuxOnTheDesktop** [comment]
Thank you for investigating. On my system, though, things are different. For - perhaps because I did not install the program 'for all users', the LucasR.exe file is here:

`/home/<myUser>/.wine/drive_c/users/nicholas/Local Settings/Application Data/Programs/LucasChessR`

And running that file directly _still_ produces the crash (!).

**Comment by LinuxOnTheDesktop** [comment]
I notice also that the LucasR.exe does not appear in the Wine configuration window:

![image](https://user-images.githubusercontent.com/47056543/108794290-66251480-757d-11eb-8073-d51d24f7e832.png)



Also, when I try to add the LucasR.exe to that list, everything seems to work but no entry actually gets added!

**Comment by loug42** [comment]
Same issue I am having with Ubuntu 20.04/Wine 5.

**Comment by lukasmonk** [comment]
I believe that the problem could be the link created.
I have edited and changed to a more simple:

[Desktop Entry]
Name=Lucas Chess R
Exec=wine "C:\Program Files (x86)\LucasChessR\bin\LucasR.exe"
Type=Application
Icon=C68D_LucasR.0
Categories=Wine;

**Comment by LinuxOnTheDesktop** [comment]
Thanks, Lucas.

But -as I said above - on my system the executable is not in that folder.

**Comment by lukasmonk** [comment]
Then try the following, replacing <WindowsUsername>

[Desktop Entry]
Name=Lucas Chess R
Exec=wine "C:\users\<WindowsUserName>\Local Settings\Application Data\Programs\LucasChessR\bin\LucasR.exe"
Type=Application
Icon=C68D_LucasR.0
Categories=Wine;

**Comment by LinuxOnTheDesktop** [comment]
Thanks, but that did not work. It failed silently but produced errors in my Linux `.xsession-errors` file. Still, those errors may have owed to replacing what was a rather complex .desktop file (which contained `Exec=env WIME PREFIX=` and then a long string containing many double slashes) with the contents you proposed. However: _I do not think the path is the issue_. For, the error message that I got originally - and which I inserted an image of above - contains the correct path and also the string 'abnormal program termination'.

**Comment by lukasmonk** [comment]
Last try:
![image](https://user-images.githubusercontent.com/6254278/110256733-beefa680-7f9a-11eb-9c27-1a33038408db.png)

**Comment by loug42** [comment]
Installed most recent release R 1.14 on Linux/Wine and on Windows 10.  Windows 10 appears to work properly (only ran it as far as the initial chess problem).  Ubuntu 20.04/Wine version crashes immediately as has been previously described.

**Comment by lukasmonk** [comment]
To clarify my previous message:



https://user-images.githubusercontent.com/6254278/110382424-2d943900-805b-11eb-8dca-f501256b320f.mov

**Comment by LinuxOnTheDesktop** [comment]
Thank you for your work, Lucas.

Your video seem intended to communicate the following. One should run the installer graphically and then run the .exe from a terminal.

That said: I noticed that in your video, you managed to launch LucasChess immediately after installation, using the installer, and not from the terminal. I and I think others on this thread have not managed to do that.

Yet, r_unning the program from the terminal did work for me_ (and I am on Mint Cinnamon). Also, _I managed_ - eventually - _to create a working launcher i.e. .desktop file_ for it (though Mint's tools for editing launchers did not help and neither did having the old version of LucasChess installed; and the program seemed not to save my colour changes either - but I suppose that last thing should go in a new bug report).

Here are the contents of my working launcher (a.k.a. .desktop) file:
```

[Desktop Entry]
Name=Lucas Chess (R)
Exec=env WINEPREFIX="/home/<myLinuxUsername>/.wine" wine "/home/<myLinuxUsername>/.wine/drive_c/users/nicholas/Local Settings/Application Data/Programs/LucasChessR/bin/LucasR.exe"
Type=Application
StartupNotify=true
Path=/home/<myUsername>/.wine/dosdevices/c:/users/<myWindowsUsername>/Local Settings/Application Data/Programs/LucasChessR/bin
Icon=AFE0_LucasR.0
StartupWMClass=lucasr.exe
```
I do suspect though that something is wrong with your packaging. So I am keeping this issue open.

**Comment by LinuxOnTheDesktop** [comment]
Update: while the launcher I created works if run from Mint's application launcher, sometimes (not always) if fails to work via the dock called 'plank' and it never works on the third-party launcher called 'ULauncher'. Inference: something is wrong with how either LucasChess, or Wine, is setting up application paths.

**Comment by lukasmonk** [comment]
>>> I do suspect though that something is wrong with your packaging.
By saying this I think you don't understand the situation, this is a program compiled specifically for windows that works on windows, but there is another program that tries to emulate it on Linux and has problems doing it.
That other program is a very useful and well-known program, but it is doing things wrong, it is not able to do the emulation correctly, or it is simply unable to automatically create a working link.
My goal with this compilation is to create a windows program that works on windows, if it worked with wine it would be better, but I don't know the wine code to correct it and support my program.

**Comment by LinuxOnTheDesktop** [comment]
Lucas: so do you think the packaging is _not_ the reason LucasChessR fails to work on Wine?

Perhaps instead you mean to say only this: you have no responsibility to make the program run on Wine. Indeed you do not. Yet - and this you say too - it would be nice if it would.

**Comment by LinuxOnTheDesktop** [comment]
I tried the new version - R01_19 - with some excitement, [having seen that it comes with a dedicated WINE installer](https://lucaschess.pythonanywhere.com/downloads).

Unfortunately, I got the same problem as I encountered on an earlier version of LucasChess (that previous version being, I think, R01_12). The problem (or at least the error message) is that when the installer completes and then tries to run the program I see the following.

![image](https://user-images.githubusercontent.com/47056543/115811047-f3061600-a3e6-11eb-9bfb-1aedf73820f2.png)

I see the same problem when I try to run the installed program from (1) its desktop icon, (2) Mint's launcher menu

My OS: Linux Mint 20.1 x64 Cinnamon.

**Comment by lukasmonk** [comment]
I can't find a solution. I hope that in the future it will be solved with a native installation.

**Comment by lukasmonk** [comment]
A linux experimental version:
https://drive.google.com/file/d/13armVyDwNPRBa6cd6DDFYwu-Ch-dmjJN/view?usp=sharing

**Comment by qubidt** [comment]
@lukasmonk I wanted to package this app to make it easier for Arch Linux users to install, but it seems the way the `UserData` directory is written to the application directory makes this a bit difficult. it would be great if the user-specific data directories could be written to the [standard config/data directories](https://wiki.archlinux.org/title/XDG_Base_Directory).

If you approve the idea but have other stuff to work on, I'm happy to tackle this with a PR

**Comment by lukasmonk** [comment]
There are two ideas now in relation to this, one is to install in the home/user, then there is no problem with UserData, the other is to always install UserData in a fixed folder, in this case, all linux distributions have the same folders to the user?, or the same environment variables, this is my doubt.

**Comment by LinuxOnTheDesktop** [comment]
Thank you for your work, Lucas.

> all linux distributions have the same folders to the user?, or the same environment variables

There is a Linux standard (to which - unfortunately - not all application adhere), according to which the data at issue belongs to this directory: `/home/<username>/.config/<yourAppName>/`.

I do not know whether there is an environmental variable the content of which is exactly that path. However, there is the environmental standard `$HOME`, which one can use to generate the above path. For, one can use the following formulation (though not if one is running as root): `$HOME/.config/<yourAppName>/`.

**Comment by lukasmonk** [comment]
Thanks for the explanation, I did not know any of this.
Laudecir Daniel is preparing a new compilation and we will take this folder into account.
