### ISSUE TITLE
Tutor uses 25% of total CPU, CPU over 90 degrees C, when it is my move and I have not moved

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschessR#25]
Screenshot using the situation (and I'm black):

![image](https://user-images.githubusercontent.com/47056543/110420240-da3ddd00-8092-11eb-9622-2f40935ec1c6.png)

One of my CPU cores was pegged, on a quad-core laptop (with an Intel i7-8550U with Spectre etc. mitigations disabled); 25% usage of total CPU availability was used by the program. My CPU hit 93 degrees centigrade. And I had had the program open for only a few minutes.

I think this is a problem inherited from the non-R version of LucasChess. I think I'll just have to disable the tutor, or use a hack to externally limit the CPU it can use.

Perhaps though I misunderstand and somehow some tutor is meant to be running before I move. [EDIT: ah yes - there is a 'work in the background option'.] Even if so, it is bad for the program to stress the computer in this way, surely.

**Comment by lukasmonk** [comment]
![image](https://user-images.githubusercontent.com/6254278/110429973-fbf78e00-80ab-11eb-963b-c53cbc0d8ed8.png)
![image](https://user-images.githubusercontent.com/6254278/110430067-1c274d00-80ac-11eb-857e-d363af3a12f4.png)

**Comment by LinuxOnTheDesktop** [comment]
Right: there are two things to disable to lower CPU usage. Thank you.

But I made this point too: _under no settings - except possibly I suppose some opt-in settings - should the program hammer a CPU that hard_. Inference: unless the user overrules it, there should be some enforced sleeping or CPU-threshold. And if possible the work should get rotated between cores.

**Comment by lukasmonk** [comment]
Stockfish has been defined to use two threads by default if the machine is 64-bit.
If you want to use another configuration: Tools, Engines, External engines, Import, Stockfish, and change the threads. Then in Options, Configuration, Tutor, change the engine to this external one (*stockfish probably or the one you named).
.
