### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by ddugovic** [lukasmonk/lucaschessR#28]
Your program is excellent.  Please consider on GitHub linking in Release Notes to your blog when you make significant changes, for example:
http://lucaschess.blogspot.com/2021/01/r-106-maia.html

**Comment by lukasmonk** [comment]
Ok.
Perhaps a copy and paste from web/downloads it is enough.

**Comment by ddugovic** [comment]
Yes please... this helps me inform Lichess developers and other developers about the latest releases of your project in a way which also gives them convenient source code access (in GitHub).
