### ISSUE TITLE
Not all lines included in bin books created with polyglot book factory

### ISSUE THREAD

**Issue by Jonathan003** [lukasmonk/lucaschessR#30]
I use the latest version of Luca Chess version R 1.17
I'm trying out the bin book making options in polyglot book factory.
I notice not all lines are included. It is important for me that al lines are included. Or at least to have an option to include all lines.  
I use the option min moves = 1 and minimum score = 0 from a pgn database of about 40000 games with won and drawn games for white.

Here are some examples of lines that are missing:
![image](https://user-images.githubusercontent.com/40061628/113476796-125ff200-947e-11eb-9262-bc39e146f433.png)
![image](https://user-images.githubusercontent.com/40061628/113476846-581cba80-947e-11eb-9ab0-b040bd343ba3.png)

The window on top (1) is the bin book and the window on the bottom (2) is the pgn where the bin book is created from, in tree view.
Like you can see lines that are not played that often are not included.

**Comment by lukasmonk** [comment]
I would understand the situation better if the examples were from Lucas Chess, which is the software I know.
And also if it had the games you have worked with and the screen with the options you have used to create the book.

**Comment by Jonathan003** [comment]
I don't know how to display the original pgn games in tree view in Lucas Chess? That's why I used SCID instead.
I will send you an email with the database and the screenshots.

**Comment by lukasmonk** [comment]
Hi Jonathan I have not received  your email.
