### ISSUE TITLE
How to add new turn on the lights 

### ISSUE THREAD

**Issue by CowboyBebug** [lukasmonk/lucaschessR#31]
Dear lucas, 
First of all, many thanks and congrats for this great software. You are a wonderful person to make this available for free. Specially I like the different training methods you've provided which I think are much better than the usual puzzle training features found elsewhere.

 What I like the most is "turn on the lights". I've completed both UNED and Uwe ones and that improved my chess a lot. 
I'm writing this because I would like to train other puzzles with turn on the lights format. Specifically, lichess has provided all of their puzzles for free [here](https://database.lichess.org/#puzzles) with a lot of metadata like rating and themes. I've already been able to add a selection of these puzzles with my rating range to personal tactics and that way I can do "learn tactics by repetition" with these puzzles. However, I think "turn on the lights" is the ultimate puzzle training format and I like to know how to add lichess puzzles with that format.

What I've found until now is [this directory ](https://github.com/lukasmonk/lucaschessR/blob/master/Resources/Trainings/Tactics%20by%20UNED%20chess%20school/Attacking%20Defender.fns) which I think I understand, but there is also [this file](https://github.com/lukasmonk/lucaschessR/blob/master/bin/Code/TurnOnLights/TurnOnLights.py#L324) that suggests after adding those fns files, I also need to modify codebase too. So, would you please be kind enough to point me in the right direction for doing this. If you like to, I would be very happy to help adding these puzzles to Lucas Chess for other people to use too.

Hope the best

**Comment by lukasmonk** [comment]
It is a huge source of puzzles, with the possibility of filtering by various concepts, preparing a program option to import into the format it works with is not very difficult. Right now I don't have time for anything except solving bugs, but it's a good idea to try in the future.

**Comment by CowboyBebug** [comment]
Thanks for your response. I wondered if I could contribute to the project if you are interested. I think I already can generate something like this [directory](https://github.com/lukasmonk/lucaschessR/tree/master/Resources/Trainings/Tactics%20by%20UNED%20chess%20school). Should I fork and do that?

**Comment by CowboyBebug** [comment]
My initial thinking is that I can generate something like that for different rating ranges. Like 1500-1600, 1600-1700, etc.

**Comment by lukasmonk** [comment]
I have to think about this, I would like to support the huge LiChess puzzle database in some way, and also advance the development of the "Turn on the ligths" training.
In the meantime one way is to hack that directory.
(I'm going to be absent from the internet for a few days in case there are more comments in this thread).

**Comment by lukasmonk** [comment]
One possibility could be to give the option in Databases to import this CSV. And from there it could be possible to generate training or fns files.
