### ISSUE TITLE
How do the GM engines work?

### ISSUE THREAD

**Issue by c0mr4de** [lukasmonk/lucaschessR#32]
I love Lucas Chess but I've been having a hard time trying to find the full documentation. I've figured how to make use of most of the stuff, but I'm wondering how the GM engines are made. Are they just taken from somewhere else or is there a method to turn database of games into a bot?

**Comment by lukasmonk** [comment]
All GM engines have been created by Michele Tumbarelo working directly with the engines assigned to each GM. Setting the right UCI options, this is the hard work. In addition each GM has his opening book (.bin polyglot file) made from his games.

**Comment by c0mr4de** [comment]
@lukasmonk Thank you for explanation! And also, thank you for developing Lucas Chess. Best chess program there is! Appreciate your great work👍
