### ISSUE TITLE
'Engine not found' error in Linux (Mint 20.04)

### ISSUE THREAD

**Issue by maclarsson** [lukasmonk/lucaschessR#33]
I followed the instructions to install LucasChessR 1.19 under Linux (Mint/Ubuntu 20.04) and got it to run.

When I start a game though, I get an error message "Engine not found" with the file name of the engine (e.g. 'OS/linux/Engines/stockfish/stockfish_13_linux_x64-bmi2').

I checked and the file exists in that folder...

Any suggestions?

**Comment by maclarsson** [comment]
Looks like I found a solution myself.

I made the main engines files executable ('chmod +x') and imported them again into the program (Tools>Engine>External Engines).

Don't know why this was not working out-of-the-box on my system :-)...

**Comment by lukasmonk** [comment]
A linux experimental version:
https://drive.google.com/file/d/13armVyDwNPRBa6cd6DDFYwu-Ch-dmjJN/view?usp=sharing

**Comment by maclarsson** [comment]
Thank you, Lucas!

Seems to work fine out of the box :-).

Will use a bit more to improve my terrible openings and report back, if I find any glitches or problems.

Does this version have any advantages with respect to speed etc. or is it primarily for convenience/compatibility?

**Comment by lukasmonk** [comment]
The speed is the same, it's about saving the whole process of installing libraries for the user, removing all that complexity.
