### ISSUE TITLE
The Linux version: packaging change very much needed, or at least a little documentation (edit: on the download page)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschessR#35]
Thank you _very much_ for the Linux version.

I am afraid that a 270MB *shell script* is problematic, at least and especially without any explanation. Others will react as I did: they will wonder, What on earth is this? Moreover, what might come to mind is: a file pretending to be something that it is not and hence which might be malware (and the file is to large to scan easily on VirusTotal.com).

Note also: in order to actually run the thing, one needs to mark it executable.

So, at the least, please tell prospective users that:

- the file is a self-extracting shell script er, thing;
- one needs to mark the file executable

and indeed

running the file will offer a 'live' mode (cf. the 'live mode' of Linux 

- installation media) and also an installer.

**Comment by LinuxOnTheDesktop** [comment]
Oh, there are instructions [here](http://lucaschess.blogspot.com/2021/05/linux-first-binary-version.html). But I got the file directly from the download page.

**Comment by lukasmonk** [comment]
Thanks.
I have added a link on the download page to the Fresh News blog.
