### ISSUE TITLE
In-game Config should be made more distinct from the global 'Options'; suggestion for an improvement

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschessR#37]
I think that the 'config' option that one sees when playing a game, which affects only that game (yes?) and which I depict below, should be labelled as something like 'Game configuration', in order to make that last point clearer. I suppose though that 'game configuration' is too long a string. But at least one could have 'Game configuration' - or 'Configuration (this game only)' - as the *tooltip*. It is easy to get overwhelmed by the number of options LucasChess offers, and it can be hard to know where to find a particular setting; the tooltip change that I propose would help a little bit with those difficulties.

![image](https://user-images.githubusercontent.com/47056543/120574112-9b5fbf00-c416-11eb-8e34-610fe5afcdca.png)

**Environment**

LucasChessR 123
Linux Mint 20.1 x64 Cinnamon
Linux kernel 5.8.0-53
```
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.3) 2.31
```

Thank you for providing a Linux version of your software.

**Comment by lukasmonk** [comment]
Config contains similar options in many places in the programme, changing it to a larger label would only be an improvement once and would only take up space the rest of the time. And if it is a long label in English, it would be longer in other languages.
