### ISSUE TITLE
Regression: the window showing the result obscures the board

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschessR#38]
**Problem**

Screenshot:

![image](https://user-images.githubusercontent.com/47056543/120909755-47501700-c670-11eb-97c5-0ee33d5ddf41.png)

Cf. https://github.com/lukasmonk/lucaschess/issues/71

**Environment**

LucasChessR 123
Linux Mint 20.1 x64 Cinnamon
Linux kernel 5.8.0-53
```
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.3) 2.31
```

**Comment by lukasmonk** [comment]
Fixed
