### ISSUE TITLE
The repository should not contain binary files

### ISSUE THREAD

**Issue by marmistrz** [lukasmonk/lucaschessR#4]
Hosting binary files in a git repo makes it unnecessarily large, doesn't allow clean diffs and may cause licensing trouble (are you sure that some of the binary only engines allow redistribution under GNU GPLv3 or at all?). I see that stockfish is provided as sources, but this will also be unnecessary for many people. Also, note that shipping proprietary engines may cause trouble for people who aren't allowed/don't want to run proprietary software. 

However, removing the blobs altogether from the repository would require rewriting history: https://stackoverflow.com/questions/62186378/how-to-remove-binary-files-from-all-of-the-bitbucket-git-history-when-the-repo

Is there any rationale for providing a ton of engines alongside with the GUI? In my opinion, it should be user's responsibility to get the engines. If you want to make onboarding easier, you might consider using a separate git repository and use git submodules.

**Comment by lukasmonk** [comment]
Sorry, this is my way of doing things for many years.
I have asked permission from all engine authors that are not GPL.
**This is the most comfortable way for me.**
The binaries are very stable, so there is not a lot of traffic on updates.
The reason there are so many engines is that it is easier to use, as far as I go.
The use of github on my part is to facilitate access to the sources to those who have an interest, I do not seek help to program, I really prefer to continue only in this aspect, it is difficult for me to adapt to the programming way of others, although always I have been open to studying the proposed changes. 
Something that I do not want to lose is the freedom to do what I consider most correct at all times, without having to consult with anyone else, that freedom is very important to me in this personal fun project.

**Comment by marmistrz** [comment]
Thanks for your reply. Sure, of course it's important to have fun while working on a project and you have the final say as it's your project.

Looking at what you've mentioned, embedding a git submodule is probably a slightly more advanced and accurate version of what you're doing. Take a look, for instance, how we embedded a testsuite from a separate repository in [this project](https://github.com/CraneStation/wasi-common/tree/9a5c53b3ed11cc3f9d58417695d72c8c7df5a1c2) and see if you like it. 

The point of these remarks is that high friction while starting to tinker with a project may discourage external contributors or packagers. It's also really nice when you don't have to do everything yourself and accept external contributions too.

Have fun on this project!

**Comment by cipherize** [comment]
> But sorry, this is my way of doing things for many years.

Then you've been doing it wrong for many years. No better time than the present to develop proper habits.

> **This is the most comfortable way for me.**

See the previous.

> Something that I do not want to lose is the freedom to do what I consider most correct at all times, without having to consult with anyone else, that freedom is very important to me in this personal fun project.

You might consider it correct, but it isn't correct. It's quite far from correct. See the first item. No better time than the present to develop proper habits.

**Comment by lukasmonk** [comment]
Thank you for expressing your opinion to try to help me.
