### ISSUE TITLE
Linux (Linux Mint Cinnamon): no maximise/minimize icon

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschessR#40]
It seems impossible to maximise, or indeed minimize, Linux chess. Screenshot:

![image](https://user-images.githubusercontent.com/47056543/121762266-baec9b00-cb2c-11eb-9d04-4c7c2323f174.png)

**Environment**

LucasChessR 123
Linux Mint 20.1 x64 Cinnamon
Linux kernel 5.8.0-53
EDIT (addition):
```
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.3) 2.31
```

**Comment by lukasmonk** [comment]
CTRL +  mouse scroll wheel over the board : this doesn't work?
Alternative: [https://youtu.be/QBrYY46tmFI](https://youtu.be/QBrYY46tmFI)

**Comment by LinuxOnTheDesktop** [comment]
I will try the CTRL combination later. I could adjust the board size. But why need I use workarounds? What is wrong with a maximize button? Other windows have them (except perhaps - I don't know - on Gnome).

**Comment by lukasmonk** [comment]
You have F11, to maximize and F11 to go back to the same size.
In Open Suse, there are a maximize button and it works:
![image](https://user-images.githubusercontent.com/6254278/121777416-33d20e00-cb92-11eb-9dd3-d2ad481416f6.png)

**Comment by LinuxOnTheDesktop** [comment]
Right. It would be nice were Mint Cinnamon to have the maximize button; and it is the desktop environment (DE), not the distribution, that is making the difference here, I think. What DE is that instance of OpenSuse using - is it Plasma (a.k.a. KDE)?

The problem here might be a Cinnamon bug - see [here](https://forums.linuxmint.com/viewtopic.php?t=218453). Still, that post suggests some hacks that the user can use in order to fix things. I will try those hacks and report back.

**Comment by lukasmonk** [comment]
I will add the possibility to change the style of the windows, I haven't tried it on Linux, but maybe it is a way to solve this problem.

**Comment by LinuxOnTheDesktop** [comment]
I do not know quite what you have in mind, but thanks.

**Comment by LinuxOnTheDesktop** [comment]
I find that if, when I first run the program, I press F11, the window goes full screen - no title bar - and I can access no controls. More: pressing F11 again did not take the program out of full-screen; I had to press F11 three or four times before things went back to normal!

**Comment by LinuxOnTheDesktop** [comment]
And ctrl-plus-scroll-action (on a touchpad; I have not tried with a mouse) does nothing.

**Comment by LinuxOnTheDesktop** [comment]
Version 1.24 still lacks a maximize button my system (and so far as I can see the user still has to work out that the installer 1) is an installer, 2) must be marked executable).

**Comment by LinuxOnTheDesktop** [comment]
Ah, there is this: 'Style of windows, added the option in Options/Configuration/general.' But changing the style - to 'fusion' - changed nothing at all (that I could see) on my system.

**Comment by LinuxOnTheDesktop** [comment]
With version 25a, I find the following.

**1** When the window style is set to 'fusion', there is a 'close' window decoration, but also the following problems. **1a** whenever the program starts, the titlebar - including the icon - is off the top of my screen. (Admittedly, I have less vertical resolution than my distribution recommends - but that is because I have to use x2 scaling because of Hi-DPI.) **1b** There is no maximise button.

**2** When the window style is set to 'Windows', the window decorations are as expected. Even maximise is present and works! But, there are strange vertical bars:

![image](https://user-images.githubusercontent.com/47056543/124056953-8f1f4f80-da1e-11eb-8ebc-50733cb74f9f.png)

Perhaps the bars are meant to be there; but they are absent when using 'fusion'.

**3** When I initiated a game with the default engine ('Rocinante'), and I was black, the computer took some ten seconds to make its first move. It was slow also to move when I was white. Perhaps I have misconfigured something. But I cannot see the configuration options - even, I think, with in-game colours set to their defaults. For, I see this:

![image](https://user-images.githubusercontent.com/47056543/124057285-14a2ff80-da1f-11eb-8a84-3ed6360888b4.png)

**Comment by lukasmonk** [comment]
Actually the one that removes the bars is the Fusion style, and it doesn't remove them, it just puts almost invisible bars.
As for the time it takes when playing without time and without limits, it is a decision of the engine, which is told that it has 10 minutes on the clock and the opponent has 10 minutes on the clock.

**Comment by LinuxOnTheDesktop** [comment]
1a and 1b _do_ seem to be problems. But, admittedly, there is option 2 (in which the bars - which may confuse the user - are by design).

The time point: I think the defaults are a poor choice and, as I said (and showed), I cannot even see those defaults.
