### ISSUE TITLE
Not able to change board colors background : Ubuntu 20.04

### ISSUE THREAD

**Issue by Arunachala-Ramana** [lukasmonk/lucaschessR#43]
Hello. I am not able to change board colors their background colors and so on. Whenever I click on those options automatically LucaschessR crashes. Attaching an animated version of the problem.

Thanks for this amazing GUI.

![Peek 2021-06-21 12-57](https://user-images.githubusercontent.com/68316708/122723521-b17fd300-d290-11eb-8f25-b3c77f3816ea.gif)

**Comment by iTzMurilo** [comment]
_The same problem also happened with another user:_ #36 
This is also happening to me, this also happens when I try to open a directory, for example, when I choose where to save a database. If I run it from the terminal, when you change the colors of the board and the program closes, the error will appear:

```
(LucasR:6840): Gtk-WARNING **: 14:33:10.640: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/gnome/16x16/status/image-missing.png: Formato de arquivo de imagem não reconhecido (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/gnome/16x16/status/image-missing.png: Formato de arquivo de imagem não reconhecido (gdk-pixbuf-error-quark, 3)
Abortado (imagem do núcleo gravada)
```

**A possible solution** is to run the program as sudo, _works for me_, this error was also happening to me in version R1.23

**Comment by Arunachala-Ramana** [comment]
Yes thanks. I did see that issue and indeed running as sudo works :) Still this is an issue and needs to be rectified. Thanks for your answer.

**Comment by lukasmonk** [comment]
Doing a google search shows that this is a fairly common bug, and there is no magic solution.
I could create a distribution specifically for ubuntu, but this slows down my updates and now the goal in the program is to achieve stability.
If the whole problem can be eliminated by launching with sudo, it doesn't seem like a big inconvenience.
If someone has a better solution, something that works on OpenSuse and Ubuntu 20.04, I'd give it a try.

**Comment by Arunachala-Ramana** [comment]
Alright no problem. Thanks for the wonderful software.
