### ISSUE TITLE
The 'stop play now' button confuses

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [lukasmonk/lucaschessR#46]
![image](https://user-images.githubusercontent.com/47056543/124057568-9bf07300-da1f-11eb-844f-a51e9a18fdb1.png)

One's eye is drawn initially to, only, the words 'play now' (!). Moreover, this problem combines in an unfortunate way with the unexpected wait for the computer to make its first move - see point 3 in [this other bug report](https://github.com/lukasmonk/lucaschessR/issues/40#issuecomment-871870112).

Lucas Chess R 1.25a
Linux Mint 20.1 Cinnamon

**Comment by LinuxOnTheDesktop** [comment]
Oh, hold on, the button not mean (i) abort the game, nor, somehow (ii) start the game, but (iii) stop [the computer thinking] and [make it] play now'. The button _should_ be labelled 'force engine move' or something like that.

**Comment by lukasmonk** [comment]
You may be right, but "Force engine move" is very long in English, in most languages it is even longer. "Play now" really is a label associated with the order to play now to the engine (stop in the engine language) and it's not a big problem if the user doesn't understand it perfectly the first time.

**Comment by LinuxOnTheDesktop** [comment]
How about the following. Go with the text 'Force move' and have that text greyed out at all time except when the engine is thinking. You would need a new icon for that text, though.

**Comment by lukasmonk** [comment]
If you can think of one, let me know, to evaluate it, right now I can't imagine any more appropriate than a stop signal, when the engine has to be told to stop, and internally a stop order has to be sent to it.

**Comment by LinuxOnTheDesktop** [comment]
The problem is trying to convey both stopping (the engine is to stop thinking) _and starting_ (the player gets to make a move) simultaneously.

Perhaps [something like this](https://duckduckgo.com/?q=stop+play&t=ffab&iar=images&iaf=type%3Aclipart%2Clicense%3AAny&iax=images&ia=images&iai=http%3A%2F%2Fcfile4.uf.tistory.com%2Fimage%2F1312F70A49B2F1271C51C1) would do.

**Comment by lukasmonk** [comment]
Thanks, I have to think about, and do some testing, although for now I like that stop sign better.
