### ISSUE TITLE
Import/Export is not working for Opening Lines

### ISSUE THREAD

**Issue by meetusadadiya** [lukasmonk/lucaschessR#5]
Hi Lucas! I really appreciate your work.

Steps to reproduce the issue:
Go to **Tools -> Openings -> Opening Lines** 
Click on 'New'
Select whatever opening move sequence you want.[In my case, its Ruy Lopez(Spanish Opening)]. Click Accept.
After naming opening, Opening Studio will open. After preparing some lines. Click on Export button, It will pop out menu written as "PGN Format", whenever I click this. Nothing happens.

Same for Import button.
I was migrating from old Lucas chess to this 'R' version. Then I found this.

**My OS:** Windows Server 2019 (64-bit)
**Processor:** Intel Xeon Platinum 8124M 36 Cores

**Comment by lukasmonk** [comment]
Hi,
I have not been able to replicate the problem.
Perhaps the problem is that you have to select a file to save.
If this is not the case, I need the bug.log file, it probably has the lines with the problem.

**Comment by meetusadadiya** [comment]
Thanks for your response.
After Maximizing the window, the export option started working. But Import option is still not working.

Here is my bug.log file.

[bug.log](https://github.com/lukasmonk/lucaschessR/files/5413100/bug.log)

**Comment by lukasmonk** [comment]
Thanks. Fixed now.

**Comment by meetusadadiya** [comment]
Yeah! It's working. Will tell you, if I find any other bugs to make this program better.
Thanks a lot!
