### ISSUE TITLE
Installed Password Stealer

### ISSUE THREAD

**Issue by hopestreetav** [lukasmonk/lucaschessR#56]
Has PWS: Win32/Lineage.gen!C.dam buried in it!!!!  A Password stealer program. Not Cool!!!!

**Comment by lukasmonk** [comment]
Please tell me which antivirus has come to this conclusion. Also which version you have scanned, and whether it is with the installer or the program installed. 

The antivirus that detected this will have a service to further analyse a particular executable, please again, send them the executable or link that caused the problem and give them a chance to re-analyse in depth.

**Comment by lukasmonk** [comment]
No communication, then I close the issue.
