### ISSUE TITLE
Opening lines - multiple moves are being played when clicking arrow keys once.

### ISSUE THREAD

**Issue by WiktorZmuda** [lukasmonk/lucaschessR#60]
This small bug is best described by pictures. Here's the initial position:
![obraz](https://user-images.githubusercontent.com/30571899/141345785-c21732f4-e442-4af7-ba32-ed7db543586f.png)
And here's the line after pressing right arrow key (once):
![obraz](https://user-images.githubusercontent.com/30571899/141345958-e8d11752-cbd5-4fa7-96bc-9f97f5a2f068.png)
And after pressing the right arrow key again it jumps a little more:
![obraz](https://user-images.githubusercontent.com/30571899/141346117-0f40ac44-f612-4799-b2c3-2a9c0da6453e.png)
Then the cycle repeats:
![obraz](https://user-images.githubusercontent.com/30571899/141346156-ef765ce2-7b4a-4477-9b18-c20bb92b38a1.png)

Happens to me on Windows 10. It used to work normally but it bugged out after one of the updates about half a year ago.

**Comment by lukasmonk** [comment]
Thank you very much, fixed in the next update.
