### ISSUE TITLE
How to load a Lua engine

### ISSUE THREAD

**Issue by rchastain** [lukasmonk/lucaschessR#65]
Hello!
I search how I could load my [Lua engine](https://gitlab.com/rchastain/luciole/-/tags/0.0.5). When I try to load directly the Lua file, I have a message saying to wait, but nothing happens. Here is [bug.log](https://github.com/lukasmonk/lucaschessR/files/7786649/bug.log).

I also tried to create a file named **luciole.sh** (I am under Linux), with this line:

`lua luciole.lua`

but it doesn't work.

I also tried to load **/usr/bin/lua**, without success. I cannot edit the entry, because the GUI hangs on the message saying to wait.

Is there a way to do that? It's with LucasChess R 1.30.

Regards.

Roland

**Comment by rchastain** [comment]
By the way, I was very glad to discover that my engine Alouette is now included in LucasChess. Be careful, version 0.1.4 in rare situations plays illegal moves. It has been fixed in [version 0.1.5](https://gitlab.com/rchastain/alouette/-/releases#0.1.5). (I am moving all my projects to GitLab.)

**Comment by lukasmonk** [comment]
Hi Roland,

There are many problems to solve to be able to install luciole as it is, I have tried several ways and it has been impossible. This type of installation is intended for windows and I have not tried it for Linux.
The alternative I have used is to create a static version, I have done it with [luastatic](https://github.com/ers35/luastatic)
I had to install the development version of lua, sudo apt install liblua5.3-dev
And then launch: ./luastatic.lua luciole.lua /usr/lib/x86_64-linux-gnu/liblua5.3.a -I/usr/include/lua5.3
It is created luciole which works like any other binary.

And thank you very much for Alouette, the idea to include it was from Laudecir Daniel, who was in charge of selecting the engines for Linux. The new version will be included in the next update.

**Comment by rchastain** [comment]
> There are many problems to solve to be able to install luciole as it is, I have tried several ways and it has been impossible. This type of installation is intended for windows and I have not tried it for Linux. The alternative I have used is to create a static version, I have done it with [luastatic](https://github.com/ers35/luastatic) I had to install the development version of lua, sudo apt install liblua5.3-dev And then launch: ./luastatic.lua luciole.lua /usr/lib/x86_64-linux-gnu/liblua5.3.a -I/usr/include/lua5.3 It is created luciole which works like any other binary.
> 
Great! I didn't know that. I will try and come back.

**Comment by rchastain** [comment]
Thank you very much for the tip about luastatic. It's great!
For information, here is my script:
```
luastatic=/home/roland/.luarocks/bin/luastatic
#luastatic=/home/roland/.luarocks/lib/luarocks/rocks-5.2/luastatic/0.0.12-1/bin/luastatic
liblua=/usr/lib64/liblua.a
inc=/usr/include/

$luastatic \
luciole.lua \
chess.lua \
strict.lua \
xfen.lua \
modules/log/log.lua \
modules/serpent/serpent.lua \
$liblua -I$inc
```
And the output: `cc -Os luciole.luastatic.c  /usr/lib64/liblua.a -rdynamic -lm -ldl -o luciole -I/usr/include/`

The binary works fine. Problem solved. I close the issue.

Regards.

Roland
