### ISSUE TITLE
Going through book in analysis

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR#67]
Hi,
It would be great if one can go through various lines of book easily in an analyzed game. Though "consult book" is an option but it shows moves only related to one position at a time. It would be great if we can explore further moves in that window.

**Comment by lukasmonk** [comment]
You can add a kibitzer, with one book several times or several books, there is no limit.

**Comment by futurelauncher** [comment]
Oh! That's awesome. Sorry, I missed it completely. 
But, still there is a problem. Though the book has many moves, kibitzer shows only best ones and not others. Is there any setting which I am missing here?

**Comment by lukasmonk** [comment]
It only shows the ones that are considered in the book. To indicate others, you can do it directly with the mouse.

![image](https://user-images.githubusercontent.com/6254278/149214098-5e4e1b6e-aa82-4ce6-8600-5eefd2b43be6.png)
e3 is not in the relation
![image](https://user-images.githubusercontent.com/6254278/149214269-db8bab3b-5a07-4e3a-b103-3fad4e1d17c0.png)

**Comment by futurelauncher** [comment]
Though e3 is not in the relation, but still if it is there in the book, it should be visible to the user. Even if you want to hide e3, you can restrict it by some setting, but for those who want to see it, it should be visible (through some setting at least).
![image](https://user-images.githubusercontent.com/60097814/149256746-9bf5583d-031a-4946-880a-2e93b596abcb.png)
All the other moves, other than e4, d4, c4, Nf3 are not visible in Lucaschess.
![image](https://user-images.githubusercontent.com/60097814/149257902-1fd1f47c-f71b-4b3c-909d-d7feae83034e.png)

**Comment by lukasmonk** [comment]
They are not visible because they would have to be invented to show them.
Perfect2021.bin does not have the same movements as Perfect2021.ctg
Bad movements have not been included.
