### ISSUE TITLE
Speed of analysis

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR#68]
Hi!
I find analyzing a game in Lucaschess too time consuming. To confirm it I analyzed a game in Scid Vs. PC, Fritz and Lucas Chess R and keeping everything constant they completed analysis in 58 sec., 1 min. 4 sec., 9 min. 50 sec. respectively. Why Lucas Chess is taking so much of time to analyze a game? Can it be lesser with some setting?

**Comment by lukasmonk** [comment]
The time used is engine time. The differences between the programmes will depend on the analysis parameters, e.g. you can set the Lucas Chess analysis with depth 4 and time 0, and it will look like a racing car.
![image](https://user-images.githubusercontent.com/6254278/149541658-5f60b357-260a-4329-bf1e-bc52de428c34.png)

If you want to compare, look at the engine thinking conditions in each of the programmes.

**Comment by futurelauncher** [comment]
Hi Lucas,
I mentioned "keeping everything constant" in the above comment. Now let me elaborate over what I kept constant. 
1) Same pc and OS for all GUIs.
2) Same game with 37 moves
3) Same side to analyze (Black)
4) Same depth i.e. 20 (time based setting was not considered in any GUI)
5) Same book
Did I miss any parameter in the comparison?

**Comment by lukasmonk** [comment]
No, the same engine version is evident.

**Comment by lukasmonk** [comment]
I imagine that the problem lies in the number of variants that are analysed in each position, if only the best one is indicated, it is faster.

![image](https://user-images.githubusercontent.com/6254278/149616681-7fab22ff-2dee-456a-8cdb-f8405a642940.png)

**Comment by lukasmonk** [comment]
As I indicate in the previous message, you have to check the MultiPV value in each of the other GUIs.

And a point:
4.Same depth i.e. 20 (time based setting was not considered in  **other GUIs**)

**Comment by futurelauncher** [comment]
Apt imagination! Multipv seems to be culprit behind consuming too much of time. Also, I used different engine versions in GUIs. After selecting 1 multipv and same engine versions in all, following are the results.
1) Scid Vs Pc - 2 min 28 sec
2) Lucaschess - 2 min 32 sec
3) Fritz - 2 min 44 sec

Thanks for the quick response!!! (which you always give)

**Comment by lukasmonk** [comment]
I know where those 4 seconds are, but it's not worth the effort.
With MultiPV = 5 it is possible to obtain an analysis where the main alternatives are valued, which for a study of the game I think is convenient.

**Comment by futurelauncher** [comment]
Ya, and even as an average user, I don't think it creates much of a difference. 
Yes, indeed 5 lines (probably default in Lucaschess) are good from analyzing perspective, but when a user like me who is indulged in BLITZ, playing 5 minutes games, can't afford to give 10 minutes for analyzing.  ;) (Just needed quick analysis with major blunders, not in-depth analysis).
