### ISSUE TITLE
Doesn't save the preferences in the game window

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR#72]
Hi,
When you paste a game and open it in software and click COFIG and later SHOW/HIDE, PGN information, captured material etc., Lucaschess doesn't save your preferences. When you next time paste another game, you have to choose those options again. I think program should remember your choices or at least there should be saving option in the window somewhere, so that we don't need to do the same thing again and again.

**Comment by lukasmonk** [comment]
Thanks, fixed, to the next update.

**Comment by futurelauncher** [comment]
My pleasure.
