### ISSUE TITLE
Remove marked arrows and highlighted boxes with right click

### ISSUE THREAD

**Issue by Arunachala-Ramana** [lukasmonk/lucaschessR#74]
The title says it all : Is it possible to remove all the marked arrows and highlighted boxes with the help of right click mouse similar to how it works on chess.com? I see that highlighting the squares and marking arrows can only be removed using the director. Let me know if there are keypad shortcuts to remove highlighted squares/arrows. At present, I am not aware.

Thanks.

**Comment by lukasmonk** [comment]
Try Ctrl-F1 and Ctrl-F2

**Comment by lukasmonk** [comment]
Also by repeating the arrow or the box.

**Comment by Arunachala-Ramana** [comment]
Ah thanks, Ctrl+F1 and Ctrl+F2 are working wonderfully. Thanks for the software, and thanks for taking time to reply.
