### ISSUE TITLE
More Shortcuts

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR#75]
Shortcuts can be created for main windows, not deep down in the windows. For e.g. if I can create shortcut for Tools - Paste pgn but cannot create it inside the game window. Say for e.g. I want to create shortcuts for "Analyze" or "Kibitzers" etc., it is not possible.

**Comment by lukasmonk** [comment]
It's not something I can implement easily.
I have added your idea to my ideas notebook.
