### ISSUE TITLE
Forgetting board size after maximization

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR#81]
Hi,
This bug is somewhat related to our previous discussion, but still different, so mentioning it separately.
Say, if I change default board size from 66 to 71 of any board, either main window board or pgn game window board and if I maximize any window, either main board window or pgn game board window and close the program, next time whenever I open it, it forgets new size 71 and goes back to its default size 66.

**Comment by lukasmonk** [comment]
I believe it is fixed in my code. To the next update.
