### ISSUE TITLE
How to configure inbuilt Chess Engine

### ISSUE THREAD

**Issue by 1ecstasy** [lukasmonk/lucaschessR#82]
Hello there,
usually the analysis feature on lichess serves my purposes just fine but today I wanted to do a more in-depth analysis so I had a look at pgn analysis feature of lucas-chess again. I noticed it to be slower than I expected and sure enough i can see from the task manager, that not one single core of my computer is fully occupied. I am pretty sure that the number of threads is not configured "correctly" however I could not find any other possibilty to configure the analysis than the dialogue appearing when clicking the analyze button.
Is there any way to configure the number of threads or for that matter other parameters that do not appear in the "Analyze"-Dialogue?

Edit: Maybe I also misunderstand the architecture behind it. I do not know whether you pass the number of threads as an argument to e.g. stockfish or rather you'd distribute the different positions from each move sequentially or in parallel to potentially multiple stockfish instances. If so maybe multiple cores/threads are just not something that is supported right now, in which case, just let me know.

Thanks very much in advance.

**Comment by lukasmonk** [comment]
Right now one option is to create an external engine copy of stockfish, and set up the threads that best suit your particular situation.
Tools/Engines/External engines
Import, Stockfish
Establish the options you think are best.
Save
Options/Configuration/Tutor and select the new engine.

**Comment by 1ecstasy** [comment]
Thanks a lot. That solves my problem :)
