### ISSUE TITLE
Adding search bar

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR#87]
Hi,
In a database, in "Players" tab, after clicking "Change", "Player" window opens. In this window we can see all players' names. If there are higher number of players, it is very difficult to scroll down/up to search one. Instead, if a search bar added, can give instant result.
![image](https://user-images.githubusercontent.com/60097814/151736786-03701c5c-29c9-45b2-9973-7d9f63aef3e8.png)

**Comment by lukasmonk** [comment]
It is possible to write the first letter.

**Comment by futurelauncher** [comment]
Yes, but the problem with that approach is if you have many entries with that letter, you have to go through all of them. It's a tedious job. In one of my databases there are more than 100 players who are starting from letter "A". So, to select a single player, I have to go through 100 players every time.

**Comment by lukasmonk** [comment]
Ok. 
To the next update of R2
