### ISSUE TITLE
Opening two separate windows at a time

### ISSUE THREAD

**Issue by futurelauncher** [lukasmonk/lucaschessR#89]
Hi,
It would be beneficial if Lucaschess acquires ability to open two separate windows at a time for e.g. if I copy pasted a game inside a temporary database and after analyzing the game, if I wanted to open "Opening lines" window just to enter new moves in any opening studio there, it should be feasible. 

Right now what I do is, I copy paste a game in pgn window, analyze it, save it in a database, open another program (Fritz), paste game there, open Opening lines studio in Lucaschess and now I add manually add the moves there by seeing the moves in Fritz window.

**Comment by lukasmonk** [comment]
You can open as many instances of Lucas Chess as you like.
You could import a pgn in Opening lines.

**Comment by futurelauncher** [comment]
Ops, my bad. I should learn Windows 10 features more. Actually I got used to Fritz more for many years, so probably expecting the same here. There you go from one module to another from same screen. For e.g. if you are analyzing a game in main window and want to open database window, you just click "Database" icon. 
![image](https://user-images.githubusercontent.com/60097814/152379650-3e12e554-f60e-40bc-9389-544ff1da9f73.png)
Anyways, my problem is solved. Thanks!

**Comment by futurelauncher** [comment]
Afterthought: Going from one window to another saves a click than opening another instance.
